const API=(window.CONTIX_CONFIG?.API_BASE_URL||"").replace(/\/$/,"");
let token=localStorage.getItem("contix_admin_token")||"", currentView="overview", editing=null;
const $=id=>document.getElementById(id);
function headers(json=true){return {"Authorization":"Bearer "+token,...(json?{"Content-Type":"application/json"}:{})}}
function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));}
async function api(path,opt={}){const r=await fetch(API+path,{...opt,headers:{...headers(opt.body!==undefined),...(opt.headers||{})}});if(r.status===401){logout();throw new Error("Session expired")}const d=await r.json();if(!r.ok)throw new Error(d.error||"Request failed");return d;}
function logout(){localStorage.removeItem("contix_admin_token");token="";$("login").classList.remove("hidden");$("app").classList.add("hidden");}
async function login(e){e.preventDefault();try{const d=await fetch(API+"/api/admin/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email:$("email").value,password:$("password").value})}).then(r=>r.json());if(!d.token)throw Error(d.error||"Login failed");token=d.token;localStorage.setItem("contix_admin_token",token);$("login").classList.add("hidden");$("app").classList.remove("hidden");show("overview");}catch(x){alert(x.message)}}
async function show(v){currentView=v;$("title").textContent={overview:"Overview",products:"Products",orders:"Orders",customers:"AI handovers",ai:"AI assistant",marketing:"Marketing",settings:"Settings"}[v];if(v==="overview")return overview();if(v==="products")return products();if(v==="orders")return orders();if(v==="customers")return handovers();if(v==="ai")return ai();if(v==="marketing")return marketing();if(v==="settings")return settings();}
async function overview(){const d=await api("/api/admin/dashboard");$("view").innerHTML=`<div class="stats">${Object.entries(d).map(([k,v])=>`<div class="stat"><span>${esc(k.replaceAll("_"," "))}</span><strong>${v}</strong></div>`).join("")}</div><div class="panel" style="margin-top:18px"><h2>Owner controls</h2><p>Add products, replace photos, change prices and stock, publish/unpublish listings, process orders and use AI assistance from the sections on the left.</p></div>`}
async function products(){const list=await api("/api/admin/products");$("view").innerHTML=`<div class="panel"><button class="btn" onclick="newProduct()">+ Add new product</button></div><div class="tablewrap" style="margin-top:15px"><table class="table"><tr><th>Photo</th><th>Product</th><th>Price</th><th>Stock</th><th>Status</th><th>Actions</th></tr>${list.map(p=>`<tr><td><img class="productimg" src="${p.images?.[0]||""}"></td><td><b>${esc(p.name)}</b><br><small>${esc(p.brand)} • ${esc(p.category)}</small></td><td>₦${p.price.toLocaleString()}</td><td>${p.stock}</td><td>${p.published?"Live":"Hidden"}</td><td class="actions"><button class="btn light" onclick='editProduct(${JSON.stringify(p).replace(/'/g,"&#39;")})'>Edit</button><button class="btn danger" onclick="deleteProduct(${p.id})">Delete</button></td></tr>`).join("")}</table></div>`}
function newProduct(){editing=null;productForm({name:"",brand:"",category:"Phones",price:0,old_price:0,stock:0,condition:"Brand New",description:"",specs:"",images:[],is_own:true,published:true,featured:false,sku:""})}
function editProduct(p){editing=p;productForm(p)}
function productForm(p){$("view").innerHTML=`<div class="panel"><h2>${editing?"Edit product":"Add product"}</h2><form id="pf" class="formgrid"><label>Name<input id="pn" value="${esc(p.name)}" required></label><label>Brand<input id="pb" value="${esc(p.brand)}"></label><label>Category<select id="pc">${["Phones","Tablets","Audio","Power","Wearables","Accessories","Computing"].map(x=>`<option ${x===p.category?"selected":""}>${x}</option>`).join("")}</select></label><label>Condition<input id="pcond" value="${esc(p.condition)}"></label><label>Price (NGN)<input id="pp" type="number" value="${p.price}"></label><label>Old price<input id="po" type="number" value="${p.old_price||0}"></label><label>Stock<input id="ps" type="number" value="${p.stock}"></label><label>SKU<input id="psku" value="${esc(p.sku)}"></label><label class="full">Description<textarea id="pd">${esc(p.description)}</textarea></label><label class="full">Specifications<textarea id="pspec">${esc(p.specs)}</textarea></label><label>Own product <input id="pown" type="checkbox" ${p.is_own?"checked":""}></label><label>Published <input id="ppub" type="checkbox" ${p.published?"checked":""}></label><label>Featured <input id="pfeat" type="checkbox" ${p.featured?"checked":""}></label><div class="full"><b>Current images</b><div style="display:flex;gap:10px;flex-wrap:wrap;margin:10px 0">${(p.images||[]).map((x,i)=>`<div><img class="productimg" src="${x}"><button type="button" class="btn danger" onclick="removeImage(${i})">Remove</button></div>`).join("")}</div><input id="pfiles" type="file" multiple accept="image/*"></div><div class="full"><button class="btn">Save product</button> <button type="button" class="btn light" onclick="products()">Cancel</button></div></form></div>`;$("pf").onsubmit=saveProduct}
function removeImage(i){if(!editing)return;editing.images.splice(i,1);productForm(editing)}
async function saveProduct(e){e.preventDefault();const p={name:$("pn").value,brand:$("pb").value,category:$("pc").value,condition:$("pcond").value,price:Number($("pp").value),old_price:Number($("po").value),stock:Number($("ps").value),sku:$("psku").value,description:$("pd").value,specs:$("pspec").value,is_own:$("pown").checked,published:$("ppub").checked,featured:$("pfeat").checked,images:editing?.images||[]};try{const d=editing?await api("/api/admin/products/"+editing.id,{method:"PUT",body:JSON.stringify(p)}):await api("/api/admin/products",{method:"POST",body:JSON.stringify(p)});const id=d.id;const files=$("pfiles").files;if(files.length){const fd=new FormData();[...files].forEach(f=>fd.append("images",f));await api("/api/admin/products/"+id+"/images",{method:"POST",headers:{"Authorization":"Bearer "+token},body:fd})}alert("Product saved.");products()}catch(x){alert(x.message)}}
async function deleteProduct(id){if(!confirm("Delete this product permanently?"))return;try{await api("/api/admin/products/"+id,{method:"DELETE"});products()}catch(x){alert(x.message)}}
async function orders(){const list=await api("/api/admin/orders");$("view").innerHTML=`<div class="tablewrap"><table class="table"><tr><th>Reference</th><th>Customer</th><th>Total</th><th>Payment</th><th>Status</th><th>Update</th></tr>${list.map(o=>`<tr><td>${esc(o.reference)}</td><td>${esc(o.customer_name)}<br><small>${esc(o.email)} ${esc(o.phone)}</small></td><td>₦${o.total.toLocaleString()}</td><td>${esc(o.payment_status)}</td><td>${esc(o.status)}</td><td><select onchange="setOrderStatus(${o.id},this.value)">${["PAYMENT_PENDING","PAID","PROCESSING","SHIPPED","DELIVERED","CANCELLED","REFUNDED"].map(s=>`<option ${s===o.status?"selected":""}>${s}</option>`).join("")}</select></td></tr>`).join("")}</table></div>`}
async function setOrderStatus(id,status){try{await api("/api/admin/orders/"+id,{method:"PATCH",body:JSON.stringify({status})})}catch(x){alert(x.message)}}
async function handovers(){const list=await api("/api/admin/handovers");$("view").innerHTML=`<div class="tablewrap"><table class="table"><tr><th>Customer</th><th>Email</th><th>Message</th><th>Status</th></tr>${list.map(x=>`<tr><td>${esc(x.customer_name)}</td><td>${esc(x.email)}</td><td style="white-space:normal;min-width:300px">${esc(x.message)}</td><td>${x.status} <button class="btn light" onclick="closeHandover(${x.id})">Close</button></td></tr>`).join("")}</table></div>`}
async function closeHandover(id){await api("/api/admin/handovers/"+id,{method:"PATCH",body:JSON.stringify({status:"CLOSED"})});handovers()}
async function ai(){ $("view").innerHTML=`<div class="panel"><h2>Private CONTIX AI assistant</h2><p>Ask it to draft customer replies, improve product descriptions, analyze catalog data or write marketing copy.</p><div id="ach" class="chatadmin"></div><div class="adminchatinput"><input id="aiin" placeholder="Ask the owner AI..."><button class="btn" onclick="askAdminAI()">Send</button></div></div>`}
async function askAdminAI(){const input=$("aiin"),box=$("ach");const text=input.value.trim();if(!text)return;input.value="";box.innerHTML+=`<div class="bubble user">${esc(text)}</div>`;try{const d=await api("/api/admin/ai",{method:"POST",body:JSON.stringify({messages:[{role:"user",content:text}]})});box.innerHTML+=`<div class="bubble">${esc(d.answer)}</div>`;box.scrollTop=box.scrollHeight}catch(x){box.innerHTML+=`<div class="bubble">${esc(x.message)}</div>`}}
async function settings(){const s=await api("/api/admin/settings");$("view").innerHTML=`<div class="panel"><form id="sf" class="formgrid">${Object.entries(s).map(([k,v])=>`<label>${esc(k)}<input name="${esc(k)}" value="${esc(v)}"></label>`).join("")}<div class="full"><button class="btn">Save settings</button></div></form></div>`;$("sf").onsubmit=async e=>{e.preventDefault();const o={};new FormData(e.target).forEach((v,k)=>o[k]=v);await api("/api/admin/settings",{method:"PUT",body:JSON.stringify(o)});alert("Settings saved.")}}
async function marketing(){const s=await api("/api/admin/settings");$("view").innerHTML=`<div class="panel"><h2>Marketing & tracking</h2><p>Store your tracking IDs here. Campaigns themselves remain under your official advertising accounts.</p><form id="mf" class="formgrid"><label>Meta Pixel ID<input name="meta_pixel_id" value="${esc(s.meta_pixel_id||"")}"></label><label>TikTok Pixel ID<input name="tiktok_pixel_id" value="${esc(s.tiktok_pixel_id||"")}"></label><label>X Pixel ID<input name="x_pixel_id" value="${esc(s.x_pixel_id||"")}"></label><label>Google Analytics ID<input name="google_analytics_id" value="${esc(s.google_analytics_id||"")}"></label><div class="full"><button class="btn">Save tracking IDs</button></div></form><hr><p><a target="_blank" href="https://ads.tiktok.com/">TikTok Ads</a> · <a target="_blank" href="https://www.facebook.com/business/ads">Meta Ads</a> · <a target="_blank" href="https://ads.x.com/">X Ads</a></p></div>`;$("mf").onsubmit=async e=>{e.preventDefault();const o={};new FormData(e.target).forEach((v,k)=>o[k]=v);await api("/api/admin/settings",{method:"PUT",body:JSON.stringify(o)});alert("Saved.")}}
document.addEventListener("DOMContentLoaded",()=>{if(token){$("login").classList.add("hidden");$("app").classList.remove("hidden");show("overview")}$("loginForm").onsubmit=login;document.querySelectorAll("[data-view]").forEach(b=>b.onclick=()=>show(b.dataset.view));$("logout").onclick=logout});
