const DEMO_PRODUCTS=[
{id:'p1',name:'iPhone 17 Pro Max',price:2150000,oldPrice:2300000,stock:8,category:'Phones',description:'Premium flagship smartphone.',images:['https://images.unsplash.com/photo-1592286927505-2fd0b4f6e6e2?auto=format&fit=crop&w=700&q=80']},
{id:'p2',name:'Samsung Galaxy S26 Ultra',price:1850000,oldPrice:1980000,stock:10,category:'Phones',description:'Flagship Android smartphone.',images:['https://images.unsplash.com/photo-1610945415295-d9bbf3a7b2d7?auto=format&fit=crop&w=700&q=80']},
{id:'p3',name:'Google Pixel Pro',price:1350000,oldPrice:1450000,stock:6,category:'Phones',description:'Google Pixel smartphone.',images:['https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=700&q=80']},
{id:'p4',name:'Premium Wireless Earbuds',price:85000,stock:20,category:'Audio',description:'Wireless earbuds with charging case.',images:['https://images.unsplash.com/photo-1606220945770-b5b6c2c55bf1?auto=format&fit=crop&w=700&q=80']},
{id:'p5',name:'Smartwatch Series 10',price:125000,stock:14,category:'Wearables',description:'Smart wearable.',images:['https://images.unsplash.com/photo-1546868871-7041f2a55e6c?auto=format&fit=crop&w=700&q=80']},
{id:'p6',name:'Android Tablet 11-inch',price:285000,stock:12,category:'Tablets',description:'Large-screen Android tablet.',images:['https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&w=700&q=80']},
{id:'p7',name:'20,000mAh Fast-Charge Power Bank',price:65000,stock:25,category:'Accessories',description:'High-capacity power bank.',images:['https://images.unsplash.com/photo-1609592424537-9b8f1d4e9a6a?auto=format&fit=crop&w=700&q=80']},
{id:'p8',name:'65W Fast Charger',price:42000,stock:30,category:'Accessories',description:'Fast USB-C charger.',images:['https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=700&q=80']}];
const get=(k,d)=>JSON.parse(localStorage.getItem(k)||JSON.stringify(d)),set=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
let products=get('contix_products',DEMO_PRODUCTS),cart=get('contix_cart',[]),orders=get('contix_orders',[]);
let settings=get('contix_settings',{paystackKey:'',supportEmail:'',headline:'Phones, gadgets and accessories in one place.',adminPassword:'King2025',handoverEmail:'',marketing:{}});
const money=n=>'₦'+Number(n||0).toLocaleString('en-NG'),save=()=>{set('contix_products',products);set('contix_cart',cart);set('contix_orders',orders);set('contix_settings',settings)};
function renderStore(){const el=document.getElementById('products');if(!el)return;const q=(document.getElementById('search')?.value||'').toLowerCase();const list=products.filter(p=>(p.name+' '+p.category).toLowerCase().includes(q));el.innerHTML=list.map(p=>`<article class="card"><img src="${p.images?.[0]||''}" alt=""><div class="card-body"><small>${p.category||''}</small><h3>${p.name}</h3><div class="price">${money(p.price)} ${p.oldPrice?`<span class="muted">${money(p.oldPrice)}</span>`:''}</div><p>${p.description||''}</p><button class="btn" onclick="addCart('${p.id}')">Order Now</button></div></article>`).join('');const cats=[...new Set(products.map(p=>p.category).filter(Boolean))];const cb=document.getElementById('categoryButtons');if(cb)cb.innerHTML=cats.map(c=>`<button onclick="filterCat('${c}')">${c}</button>`).join('');document.getElementById('cartCount')?.replaceChildren(document.createTextNode(cart.reduce((a,x)=>a+x.qty,0)));document.getElementById('year')?.replaceChildren(document.createTextNode(new Date().getFullYear()))}
function filterCat(c){document.getElementById('search').value=c;renderStore()}
function addCart(id){const p=products.find(x=>x.id===id);if(!p)return;const x=cart.find(x=>x.id===id);if(x)x.qty++;else cart.push({id,qty:1});save();alert('Added to cart');renderStore()}
function renderCart(){const el=document.getElementById('cart');if(!el)return;el.innerHTML=cart.map(x=>{const p=products.find(p=>p.id===x.id);return p?`<div class="card-body"><b>${p.name}</b> × ${x.qty} — ${money(p.price*x.qty)} <button onclick="removeCart('${p.id}')">Remove</button></div>`:''}).join('')}
function removeCart(id){cart=cart.filter(x=>x.id!==id);save();renderCart()}
document.getElementById('checkout')?.addEventListener('submit',e=>{e.preventDefault();if(!cart.length)return alert('Your cart is empty.');const cust=Object.fromEntries(new FormData(e.target));const total=cart.reduce((s,x)=>s+(products.find(p=>p.id===x.id)?.price||0)*x.qty,0);orders.unshift({id:'ORD-'+Date.now(),customer:cust,items:cart,total,status:'Awaiting Payment',created:new Date().toISOString()});cart=[];save();alert('Order created. Connect the secure Paystack backend to complete live payment verification.');location.href='index.html'});
function openProduct(id){const p=products.find(x=>x.id===id);document.getElementById('productModal').style.display='flex';document.getElementById('modalTitle').textContent=p?'Edit Product':'Add Product';document.getElementById('pid').value=p?.id||'';document.getElementById('pname').value=p?.name||'';document.getElementById('price').value=p?.price||'';document.getElementById('oldPrice').value=p?.oldPrice||'';document.getElementById('stock').value=p?.stock??'';document.getElementById('category').value=p?.category||'';document.getElementById('description').value=p?.description||'';document.getElementById('imagePreview').innerHTML=(p?.images||[]).map(i=>`<img src="${i}">`).join('')}
function closeProduct(){document.getElementById('productModal').style.display='none'}
function previewImages(){const el=document.getElementById('imagePreview');el.innerHTML='';[...document.getElementById('images').files].forEach(f=>{const r=new FileReader();r.onload=e=>el.innerHTML+=`<img src="${e.target.result}">`;r.readAsDataURL(f)})}
document.getElementById('productForm')?.addEventListener('submit',e=>{e.preventDefault();const id=document.getElementById('pid').value||'p-'+Date.now(),old=products.find(p=>p.id===id),files=[...document.getElementById('images').files],imgs=old?.images||[];if(files.length){const out=[];let pending=files.length;files.forEach(f=>{const r=new FileReader();r.onload=ev=>{out.push(ev.target.result);if(!--pending)saveProduct(id,out)};r.readAsDataURL(f)})}else saveProduct(id,imgs)});
function saveProduct(id,imgs){const p={id,name:document.getElementById('pname').value,price:+document.getElementById('price').value,oldPrice:+document.getElementById('oldPrice').value||0,stock:+document.getElementById('stock').value||0,category:document.getElementById('category').value,description:document.getElementById('description').value,images:imgs};const i=products.findIndex(x=>x.id===id);if(i>=0)products[i]=p;else products.unshift(p);save();closeProduct();renderAdmin();renderStore()}
function deleteProduct(id){if(confirm('Delete this product?')){products=products.filter(p=>p.id!==id);save();renderAdmin()}}
function renderAdmin(){const t=document.getElementById('productTable');if(!t)return;document.getElementById('statProducts').textContent=products.length;document.getElementById('statOrders').textContent=orders.length;document.getElementById('statCustomers').textContent=new Set(orders.map(o=>o.customer?.email)).size;t.innerHTML=`<table class="table"><tr><th>Product</th><th>Price</th><th>Stock</th><th>Actions</th></tr>${products.map(p=>`<tr><td>${p.name}</td><td>${money(p.price)}</td><td>${p.stock}</td><td><button class="small-btn" onclick="openProduct('${p.id}')">Edit</button> <button class="small-btn" onclick="deleteProduct('${p.id}')">Delete</button></td></tr>`).join('')}</table>`;const ot=document.getElementById('ordersTable');ot.innerHTML=orders.length?`<table class="table"><tr><th>Order</th><th>Customer</th><th>Total</th><th>Status</th></tr>${orders.map(o=>`<tr><td>${o.id}</td><td>${o.customer?.name||''}<br>${o.customer?.email||''}</td><td>${money(o.total)}</td><td>${o.status}</td></tr>`).join('')}</table>`:'<p>No orders yet.</p>'}
function sendAI(){const input=document.getElementById('aiInput'),m=input.value.trim();if(!m)return;const box=document.getElementById('chatMessages');box.innerHTML+=`<div class="bubble user">${m}</div>`;const l=m.toLowerCase();let reply='I can help with products, prices, availability and delivery. If you need a representative, request human support.';const p=products.find(x=>l.includes(x.name.toLowerCase()));if(p)reply=`${p.name} is listed at ${money(p.price)} and currently has ${p.stock} unit(s) shown in the store.`;if(l.includes('human')||l.includes('agent')||l.includes('person'))reply='I will hand this conversation to a CONTIX representative.';box.innerHTML+=`<div class="bubble ai">${reply}</div>`;input.value=''}
function handover(){document.getElementById('handoverStatus').textContent='Conversation marked for human support. In production this will notify your configured email/inbox.'}
function savePayment(){settings.paystackKey=document.getElementById('paystackKey').value.trim();save();alert('Payment setting saved')}
function saveMarketing(){settings.marketing={tiktok:document.getElementById('tiktok').value,meta:document.getElementById('meta').value,xpixel:document.getElementById('xpixel').value,ga:document.getElementById('ga').value};save();document.getElementById('marketingStatus').textContent='Saved'}
function saveStore(){settings.headline=document.getElementById('headline').value;settings.supportEmail=document.getElementById('supportEmail').value;settings.storeDesc=document.getElementById('storeDesc').value;save();alert('Store settings saved')}
function saveSettings(){settings.adminPassword=document.getElementById('adminPassword').value;settings.handoverEmail=document.getElementById('handoverEmail').value;save();alert('Settings saved')}
if(document.getElementById('products')){document.getElementById('search')?.addEventListener('input',renderStore);renderStore()}if(document.getElementById('cart'))renderCart();if(document.getElementById('productTable')){document.getElementById('paystackKey').value=settings.paystackKey||'';document.getElementById('headline').value=settings.headline||'';document.getElementById('supportEmail').value=settings.supportEmail||'';document.getElementById('storeDesc').value=settings.storeDesc||'';document.getElementById('adminPassword').value=settings.adminPassword||'';document.getElementById('handoverEmail').value=settings.handoverEmail||'';const m=settings.marketing||{};document.getElementById('tiktok').value=m.tiktok||'';document.getElementById('meta').value=m.meta||'';document.getElementById('xpixel').value=m.xpixel||'';document.getElementById('ga').value=m.ga||'';renderAdmin()}
