const ADMIN_PASSWORD="contix123";const K={p:"ctx_products",c:"ctx_cart",s:"ctx_settings",o:"ctx_orders"};
const defaults=[{id:"1",name:"iPhone 16 Pro Max",price:1299,storage:"256GB",display:"6.9\" Display",network:"5G",image:""},{id:"2",name:"Samsung Galaxy S25 Ultra",price:1249,storage:"256GB",display:"6.8\" Display",network:"5G",image:""},{id:"3",name:"Google Pixel 9 Pro",price:999,storage:"256GB",display:"6.3\" Display",network:"5G",image:""},{id:"4",name:"OnePlus 13",price:899,storage:"256GB",display:"6.8\" Display",network:"5G",image:""}];const defs={bankName:"Access Bank",accountName:"Contix Phones Ltd",accountNumber:"0123456789",email:"admin@contixphones.com"};
const get=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}},set=(k,v)=>localStorage.setItem(k,JSON.stringify(v)),ps=()=>{let x=get(K.p,null);if(!x){x=defaults;set(K.p,x)}return x},st=()=>{let x=get(K.s,null);if(!x){x=defs;set(K.s,x)}return x},cr=()=>get(K.c,[]),money=n=>"$"+Number(n).toLocaleString("en-US",{minimumFractionDigits:2}),esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[m]));
function count(){let e=document.getElementById("cartCount");if(e)e.textContent=cr().reduce((a,x)=>a+x.q,0)}function add(id){let c=cr(),x=c.find(a=>a.id===id);x?x.q++:c.push({id,q:1});set(K.c,c);count();alert("Added to cart")}
function productPic(p){return p.image?`<img src="${p.image}" alt="${esc(p.name)}">`:`<div class="placeholder">📱</div>`}
function renderProducts(){let g=document.getElementById("productsGrid");if(!g)return;g.innerHTML=ps().map(p=>`<article class="product"><div class="pic">${productPic(p)}</div><h3>${esc(p.name)}</h3><div class="spec">${esc(p.storage)} | ${esc(p.display)} | ${esc(p.network)}</div><div class="price">${money(p.price)}</div><button class="btn" onclick="add('${p.id}')">🛒 Pre-Order Now</button></article>`).join("")}
function bankHTML(){let s=st();return `<div><small>Bank Name</small><b>${esc(s.bankName)}</b></div><div><small>Account Name</small><b>${esc(s.accountName)}</b></div><div><small>Account Number</small><b>${esc(s.accountNumber)}</b></div>`}
function publicBank(){let b=document.getElementById("bank"),e=document.getElementById("email"),ce=document.getElementById("contactEmail");if(b)b.innerHTML=bankHTML();if(e)e.textContent=st().email;if(ce)ce.textContent=st().email}
function renderCart(){count();let box=document.getElementById("cartItems");if(!box)return;let c=cr(),total=0;if(!c.length){box.innerHTML='<div class="card" style="padding:30px">Your cart is empty. <a href="index.html#products">Browse products →</a></div>';document.getElementById("total").textContent=money(0);return}box.innerHTML=c.map(i=>{let p=ps().find(x=>x.id===i.id);if(!p)return"";total+=p.price*i.q;return `<div class="cartRow"><div>${p.image?`<img src="${p.image}">`:'📱'}</div><div><h3>${esc(p.name)}</h3><small>${esc(p.storage)}</small></div><div class="qty"><button onclick="qty('${p.id}',-1)">−</button><b>${i.q}</b><button onclick="qty('${p.id}',1)">+</button></div><strong>${money(p.price*i.q)}</strong><button class="btn ghost" onclick="removeItem('${p.id}')">Remove</button></div>`}).join("");document.getElementById("total").textContent=money(total);let cb=document.getElementById("checkoutBank");if(cb)cb.innerHTML=bankHTML()}
function qty(id,d){let c=cr(),x=c.find(a=>a.id===id);x.q+=d;if(x.q<1)c=c.filter(a=>a.id!==id);set(K.c,c);renderCart()}function removeItem(id){set(K.c,cr().filter(a=>a.id!==id));renderCart()}
function checkout(){let b=document.getElementById("checkout"),m=document.getElementById("modal");if(!b)return;b.onclick=()=>{if(!cr().length)return alert("Your cart is empty");m.hidden=false};m.querySelector(".close").onclick=()=>m.hidden=true;document.getElementById("orderForm").onsubmit=e=>{e.preventDefault();let total=cr().reduce((a,i)=>{let p=ps().find(x=>x.id===i.id);return a+p.price*i.q},0),o={number:"CTX-"+Date.now().toString().slice(-8),name:name.value,email:mail.value,phone:phone.value,address:address.value,total,items:cr(),date:new Date().toISOString()};let os=get(K.o,[]);os.unshift(o);set(K.o,os);set(K.c,[]);count();document.getElementById("success").innerHTML=`<div class="card"><b>Order ${o.number} created.</b><p>Total: ${money(o.total)}</p><p>Transfer the amount to the account above, then email your payment confirmation to ${esc(st().email)}.</p></div>`}}
function admin(){let lf=document.getElementById("loginForm");if(!lf)return;if(sessionStorage.ctxadmin==="1")showDash();lf.onsubmit=e=>{e.preventDefault();if(password.value===ADMIN_PASSWORD){sessionStorage.ctxadmin="1";showDash()}else alert("Incorrect password")};document.getElementById("logout").onclick=()=>{sessionStorage.removeItem("ctxadmin");location.reload()};document.querySelectorAll(".tabs button").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tabs button").forEach(x=>x.classList.remove("active"));b.classList.add("active");productsTab.hidden=paymentsTab.hidden=ordersTab.hidden=true;document.getElementById(b.dataset.tab+"Tab").hidden=false})}
function showDash(){login.hidden=true;dashboard.hidden=false;renderAdmin();fillSettings();renderOrders()}
function renderAdmin(){let box=document.getElementById("adminProducts");if(!box)return;box.innerHTML=ps().map(p=>`<article class="adminProduct">${p.image?`<img src="${p.image}">`:`<div class="adminPic">📱</div>`}<div class="adminBody"><h3>${esc(p.name)}</h3><p>${money(p.price)} · ${esc(p.storage)}</p><div class="actions"><button onclick="edit('${p.id}')">Edit</button><button onclick="del('${p.id}')">Delete</button></div></div></article>`).join("")}
function fillSettings(){let s=st();bankName.value=s.bankName;accountName.value=s.accountName;accountNumber.value=s.accountNumber;adminEmail.value=s.email}function saveSettings(){paymentForm.onsubmit=e=>{e.preventDefault();set(K.s,{bankName:bankName.value,accountName:accountName.value,accountNumber:accountNumber.value,email:adminEmail.value});alert("Saved")}}
function renderOrders(){let b=document.getElementById("orders");if(!b)return;let os=get(K.o,[]);b.innerHTML=os.length?os.map(o=>`<div class="order"><b>${o.number}</b><p>${esc(o.name)} · ${esc(o.email)} · ${esc(o.phone)}</p><p>Total: <b>${money(o.total)}</b></p><p>${esc(o.address)}</p></div>`).join(""):"<p>No orders yet.</p>"}
function modal(p){productModal.hidden=false;pid.value=p?.id||"";pname.value=p?.name||"";pprice.value=p?.price||"";pstorage.value=p?.storage||"";pdisplay.value=p?.display||"";pnetwork.value=p?.network||"";pdesc.value=p?.description||"";pimage.value="";preview.innerHTML=p?.image?`<img src="${p.image}">`:""}function edit(id){modal(ps().find(p=>p.id===id))}function del(id){if(confirm("Delete product?")){set(K.p,ps().filter(p=>p.id!==id));renderAdmin();renderProducts()}}
function productForm(){let addb=document.getElementById("add");if(!addb)return;addb.onclick=()=>modal();productModal.querySelector(".close").onclick=()=>productModal.hidden=true;pimage.onchange=()=>{let f=pimage.files[0];if(!f)return;let r=new FileReader();r.onload=()=>preview.innerHTML=`<img src="${r.result}">`;r.readAsDataURL(f)};document.getElementById("productForm").onsubmit=e=>{e.preventDefault();let id=pid.value||Date.now().toString(),old=ps().find(p=>p.id===id),save=img=>{let p={id,name:pname.value,price:Number(pprice.value),storage:pstorage.value,display:pdisplay.value,network:pnetwork.value,description:pdesc.value,image:img||old?.image||""};set(K.p,[...ps().filter(x=>x.id!==id),p]);productModal.hidden=true;renderAdmin();renderProducts()};if(pimage.files[0]){let r=new FileReader();r.onload=()=>save(r.result);r.readAsDataURL(pimage.files[0])}else save()}}
document.addEventListener("DOMContentLoaded",()=>{count();renderProducts();publicBank();renderCart();checkout();admin();saveSettings();productForm()});
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
